
// function Generate() {
// }
function Generate() {
    
var rotetor = Math.floor(Math.random ()*10);
console.log (rotetor)
if (rotetor == 0) {
 document.getElementById ('Title').innerHTML=' “Be yourself; everyone else is already taken.” ';
 document.getElementById ('autherName').innerHTML='― Oscar Wilde' ;
}
else if 
(rotetor == 1) {
    document.getElementById ('Title').innerHTML="“I'm selfish, impatient and a little insecure. I make mistakes, I am out of control and at times hard to handle. But if you can't handle me at my worst, then you sure as hell don't deserve me at my best.” ";
    document.getElementById ('autherName').innerHTML='― Marilyn Monroe' ;

}
else if 
(rotetor == 2) {
    document.getElementById ('Title').innerHTML="“Two things are infinite: the universe and human stupidity; and I'm not sure about the universe.” ";
    document.getElementById ('autherName').innerHTML='― Albert Einstein' ;

}
else if 
(rotetor == 3) {
    document.getElementById ('Title').innerHTML="“So many books, so little time.”";
    document.getElementById ('autherName').innerHTML='― Frank Zappa' ;

}
else if 
(rotetor == 4) {
    document.getElementById ('Title').innerHTML="“A room without books is like a body without a soul.”";
    document.getElementById ('autherName').innerHTML='― Marcus Tullius Cicero' ;

}
else if 
(rotetor == 5) {
    document.getElementById ('Title').innerHTML="“Be who you are and say what you feel, because those who mind don't matter, and those who matter don't mind.”";
    document.getElementById ('autherName').innerHTML='― Bernard M. Baruch' ;

}
else if 
(rotetor == 5) {
    document.getElementById ('Title').innerHTML="“You know you're in love when you can't fall asleep because reality is finally better than your dreams.”";
    document.getElementById ('autherName').innerHTML='― Dr. Seuss' ;

}
else if 
(rotetor == 6) {
    document.getElementById ('Title').innerHTML="“You only live once, but if you do it right, once is enough.”";
    document.getElementById ('autherName').innerHTML='― Mae West' ;

}
else if 
(rotetor == 7) {
    document.getElementById ('Title').innerHTML="“Be the change that you wish to see in the world.”";
    document.getElementById ('autherName').innerHTML='― Mahatma Gandhi' ;

}
else if 
(rotetor == 8) {
    document.getElementById ('Title').innerHTML="“In three words I can sum up everything I've learned about life: it goes on.”";
    document.getElementById ('autherName').innerHTML='― Robert Frost' ;

}
else if 
(rotetor == 9) {
    document.getElementById ('Title').innerHTML="“If you tell the truth, you don't have to remember anything.”";
    document.getElementById ('autherName').innerHTML='― Mark Twain' ;

}
else if 
(rotetor == 10) {
    document.getElementById ('Title').innerHTML="“A friend is someone who knows all about you and still loves you.”";
    document.getElementById ('autherName').innerHTML='― Elbert Hubbard' ;

}
}
